### ISSUE TITLE
TimeLimitError despite setting config["fail_at_total_time"]: false

### ISSUE THREAD

**Issue by arnabmutsuddy** [CovertLab/vEcoli#242]
Running workflow.py with config["total_time"] < 3000.00 results in TimeLimitError even when config["fail_at_total_time"] is set to false. This doesn't happen if total_time >= 3000. Also, ecoli_master_sim.py runs without any issue for "total_time" as low as 20. Is it possible that workflow.py is overwriting config["fail_at_toal_time"] under specific conditions? Commenting out lines 889,890 in ecoli_master_sim.py seems to provide a temporary solution.

**Comment by arnabmutsuddy** [comment]
@thalassemia any thoughts on why this might be happening?

**Comment by thalassemia** [comment]
Good catch! This is due to some sneaky undocumented behavior with `workflow.py`. The [nextflow job template](https://github.com/CovertLab/vEcoli/blob/10a03f36ae73927a2bbf96ec8ab2c29ff54f014e/runscripts/nextflow/sim.nf#L89) for simulations automatically adds the `fail_at_total_time` flag. I did this to give a more informative error message to Nextflow when a cell fails to divide within `total_time` of its birth. Even if `fail_at_total_time` were allowed to be False, Nextflow would still record the job as failed because it would not be able to find the required daughter cell JSONs for the next generation of sims, resulting in a more confusing error message. Since giving the user control over `fail_at_total_time` would not change the end result, I might just need to add a note to the documentation saying that `fail_at_total_time` has no effect with `workflow.py`.

**Comment by thalassemia** [comment]
This functionality is actually most important for isolated, full cell cycle simulations. This way, cells that fail to divide in the user-specified time limit will give the user a more informative error than a Nextflow error about missing files (daughter cell states). In colony simulations (not implemented yet in `workflow.py`), there is no clean way to parallelize over multiple Nextflow jobs, so, as a first pass, everything will just be run in one job and the whole colony simulation will terminate once the time limit is reached. My plan is to run a colony simulation if `generations` is None and a standard lineage simulations if not.

Unfortunately, I just realized that I forgot to copy and paste [the logic](https://github.com/CovertLab/vEcoli/blob/10a03f36ae73927a2bbf96ec8ab2c29ff54f014e/runscripts/nextflow/config.template#L20-L23) to make Nextflow ignore errors and keep running other simulations into [the profile that is used](https://github.com/CovertLab/vEcoli/blob/10a03f36ae73927a2bbf96ec8ab2c29ff54f014e/runscripts/nextflow/config.template#L84-L89) when running on a local machine. I'll make a PR for that, after which you should just be able to ignore any expected TimeLimitErrors and continue with your next batch of simulations.

The Parquet output failing to save is strange. By default, the Parquet emitter saves a file every 400 simulated seconds ([can be configured](https://github.com/CovertLab/vEcoli/blob/10a03f36ae73927a2bbf96ec8ab2c29ff54f014e/ecoli/library/parquet_emitter.py#L665-L681)), but it also [has some logic](https://github.com/CovertLab/vEcoli/blob/10a03f36ae73927a2bbf96ec8ab2c29ff54f014e/ecoli/library/parquet_emitter.py#L697-L770) that is supposed to save any previously unsaved data when the simulation process terminates. Is output missing for the cell that reached the TimeLimitError, concurrent simulations that were being incorrectly terminated by Nextflow when that one cell failed, or both?

Just as an aside, I would try to make sure that you run a couple of generations of simulations first to create a variety of initial states to start your short simulations from. Otherwise, there could be some biases in the default initial state that bias your screen results.

**Comment by thalassemia** [comment]
After thinking this over, I changed `fail_at_total_time` to behave consistently for individual sims and workflows (#241). Setting it to `False` should now always avoid the `TimeLimitError`. Additionally, I configured Nextflow to ignore failed jobs on all platforms, including local machines. This allows jobs that do not depend on the failed job to continue running (e.g. many variants/seeds and one fails).

The caveat is that ignored jobs do not raise an error upon workflow completion in the current stable release (24.04) of Nextflow (#240). You can either manually inspect the Nextflow run output (see [here](https://covertlab.github.io/vEcoli/workflows.html#progress) and [here](https://covertlab.github.io/vEcoli/workflows.html#id9)) for failed (ignored) jobs or [update to the latest edge release of Nextflow](https://www.nextflow.io/docs/latest/install.html#stable-and-edge-releases) to get an error message for ignored jobs at workflow termination.
